/** Mock data only — replace with API later. */
window.SKONGA_MOCK = {
  overview: {
    usersTotal: 128,
    usersNew7d: 14,
    chatsToday: 86,
    likeRate7d: 0.78,
    openReports: 3,
    ragOkRate: 0.91,
  },
  services: [
    { name: "AI Backend", url: "skonga-backend-v2.onrender.com", status: "ok" },
    { name: "Auth-content", url: "skonga-auth-content-service.onrender.com", status: "ok" },
    { name: "Library API", url: "skonga-service-api.onrender.com", status: "ok" },
    { name: "Analytics", url: "—", status: "off" },
    { name: "Scheduler", url: "—", status: "off" },
  ],
  users: [
    { id: "319da9eb", email: "shabanihamidu19@gmail.com", name: "Shebby19", plan: "free", status: "active", created: "2026-08-18" },
    { id: "34b48edf", email: "trial@test.com", name: "Trial", plan: "free", status: "active", created: "2026-08-18" },
    { id: "a1b2c3d4", email: "student@example.com", name: "Asha M.", plan: "pro", status: "active", created: "2026-08-20" },
  ],
  usage: {
    free: { chat: 20, scan: 5, image: 2, rag: 30 },
    pro: { chat: 500, scan: 100, image: 50, rag: 1000 },
    today: { chats: 86, scans: 12, images: 3, ragHits: 54 },
  },
  library: {
    version: "2.3.0",
    subjectsLoaded: 25,
    authMode: "open",
    lastOkAt: "2026-08-23T16:15:00Z",
    lastError: null,
  },
  learn: {
    activePaths: 42,
    avgMastery: 1.2,
    topSubjects: ["biology", "physics", "mathematics"],
  },
  feedback: [
    {
      id: "fb1",
      at: "2026-08-23T19:42:00Z",
      user: "Shebby19",
      vote: "like",
      userText: "Hey...ni ipi mada ya tatu physics form four",
      replyText: "Mada ya tatu ya Physics Form Four ni Alternating Current.",
      curriculumAligned: true,
      citationCount: 3,
      provider: "groq",
    },
    {
      id: "fb2",
      at: "2026-08-22T21:10:00Z",
      user: "Asha M.",
      vote: "dislike",
      userText: "what is new in Tanzanian secondary schools from net",
      replyText: "Generic education news without sources…",
      curriculumAligned: false,
      citationCount: 0,
      provider: "groq",
    },
    {
      id: "fb3",
      at: "2026-08-22T18:00:00Z",
      user: "Trial",
      vote: "like",
      userText: "Eleza photosynthesis Form 2",
      replyText: "Photosynthesis ni mchakato…",
      curriculumAligned: true,
      citationCount: 5,
      provider: "groq",
    },
  ],
  reports: [
    {
      id: "rp1",
      at: "2026-08-22T21:12:00Z",
      user: "Asha M.",
      reason: "no_sources",
      status: "open",
      note: "",
      snippet: "from net query — no Tavily cards",
    },
    {
      id: "rp2",
      at: "2026-08-21T10:00:00Z",
      user: "Trial",
      reason: "wrong_form",
      status: "triaged",
      note: "Was Form 1 intro; Library v2.3 fixed first-topic",
      snippet: "topic ya kwanza Biology form four",
    },
    {
      id: "rp3",
      at: "2026-08-20T14:30:00Z",
      user: "Shebby19",
      reason: "bug",
      status: "resolved",
      note: "Continue button — fixed in app patch",
      snippet: "Pro modal Continue unclickable",
    },
  ],
  settings: {
    maintenanceMode: false,
    features: {
      libraryRag: true,
      liveSearch: true,
      learnPath: true,
      imageGen: true,
      feedback: true,
      reports: true,
    },
    quotas: {
      freeChat: 20,
      freeScan: 5,
      freeImage: 2,
      freeRag: 30,
    },
    feedbackRetainDays: 30,
  },
};
